import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Navbar from '../components/Navbar';


export default function Home() {

  const DEVlogo = '/public/graphics/logos/dev_logo.png';
  const staticProfileImage = '/public/graphics/images/sonnenbild.jpg';
  
  return (
    <div>
      <Head>
        <title>NEXT FREI:raum (Alpha)</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Navbar devLogo={DEVlogo} profileImage={staticProfileImage} />  



      <main className={styles.main}>
        
      </main>

      <h1>Hi, WKD!</h1>

      <footer className={styles.footer}>
      </footer>


    </div>
  )
}
